class Locators():
    Register_xp = "//a[text()='Register']"
    Firstname_id = "customer.firstName"
    Lastname_id = "customer.lastName"
    address_id = "customer.address.street"
    city_id = "customer.address.city"
    state_id = "customer.address.state"
    zip_code_id = "customer.address.zipCode"
    phone_id = "customer.phoneNumber"
    Snn_id = "customer.ssn"
    username_id = "customer.username"
    pwd_id = "customer.password"
    conform_id = "repeatedPassword"
    register_xpath ="//input[@value='Register']"
    Logout = "//a[text()='Log Out']"
    UserName = "//input[@name='username']"
    Password = "//input[@name='password']"
    Login_btn = "//input[@type='submit']"
    billpay_xp = "//a[text()='Bill Pay']"
    Payeename_name = "payee.name"
    addressss_name = "payee.address.street"
    city_name = "payee.address.city"
    state_name = "payee.address.state"
    zipcode_name = "payee.address.zipCode"
    phone_name = "payee.phoneNumber"
    accountname_name = "payee.accountNumber"
    verifyaccount_name = "verifyAccount"
    amount_name = "amount"
    sendpayment_xp = "//input[@value='Send Payment']"
    Opennewaccount_xpath = "//a[text()='Open New Account']"
    Accounttype_id = "type"
    Existingaccount_id = "fromAccountId"
    Newaccount_xpath = "//input[@value = 'Open New Account']"
    messageicon_lt = "contact"
    name_id = "name"
    email_id = "email"
    Phone_id = "phone"
    message_id = "message"
    sendtocc_xpath = "//input[@value='Send to Customer Care']"
    text_xapth = "//p[text()='A Customer Care Representative will be contacting you.']"
    updater = "//a[text()='Update Contact Info']"
    mobilen = "customer.phoneNumber"
    updat = "//input[@value='Update Profile']"
    reques = "//a[text()='Request Loan']"
    loa = "amount"
    downp = "downPayment"
    appl = "//input[@value='Apply Now']"